import { ASSET_MAP } from "./assetMap";

// Appwrite Storage URL helpers.
//
// Appwrite storage is FLAT — there are no folder paths, only file ids. The
// original code passed human-readable paths like "Homepage/hero-poster.jpg",
// and those paths are hardcoded across 17 files, so rather than editing every
// call site we map path -> fileId here.
//
// ASSET_MAP is generated by migrate/migrate-assets.mjs. After uploading a new
// asset, re-run that script and copy the regenerated file over utils/assetMap.ts.

const ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT;
const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID;

function appwriteFileUrl(bucketId: string, fileId: string): string {
  return `${ENDPOINT}/storage/buckets/${bucketId}/files/${fileId}/view?project=${PROJECT_ID}`;
}

/**
 * Appwrite image transformation. Returns a resized, re-encoded variant served
 * from Appwrite's CDN instead of the full-size original.
 *
 * Card thumbnails don't need 4000px camera JPEGs — this is the difference
 * between a 2 MB download and roughly 80 KB. It also spares Next's optimiser
 * from downloading the original just to shrink it.
 */
export function getPreviewUrl(
  viewUrl: string,
  {
    width = 640,
    quality = 75,
    output = "webp",
  }: {
    width?: number;
    quality?: number;
    output?: "avif" | "webp" | "jpg" | "png";
  } = {},
): string {
  if (!viewUrl?.includes("/files/")) return viewUrl;
  const preview = viewUrl.replace("/view?", "/preview?");
  return `${preview}&width=${width}&quality=${quality}&output=${output}`;
}

/**
 * Site assets — logos, banners, hero video, UI graphics.
 * Takes the same path it always did, e.g. "Homepage/lightshardleft.png".
 */
/**
 * Site assets — logos, banners, hero video, UI graphics.
 *
 * Pass a `width` to get an Appwrite-transformed variant instead of the
 * original. Worth doing for anything large: several banners are 7-19 MB PNGs,
 * and Next's optimiser has to download the whole thing before it can resize —
 * on the server, on first request. Handing it (or the browser) a pre-sized
 * WebP removes that entirely.
 *
 * Videos and SVGs are returned untouched; Appwrite's preview endpoint only
 * transforms raster images.
 */
export function getAssetsStorageUrl(
  path: string,
  opts?: { width?: number; quality?: number },
): string {
  const fileId = ASSET_MAP[path];
  if (!fileId) {
    // Loud in development, silent in production: a missing asset should be
    // obvious while building but shouldn't spam production logs on every render.
    if (process.env.NODE_ENV !== "production") {
      console.warn(
        `[assets] No Appwrite file mapped for "${path}". ` +
          `Re-run migrate/migrate-assets.mjs and update utils/assetMap.ts.`,
      );
    }
    return "";
  }

  const url = appwriteFileUrl("assets", fileId);
  if (!opts?.width) return url;

  // Leave videos and vectors alone — nothing to resize, and asking Appwrite to
  // transform them returns an error rather than the file.
  if (/\.(mp4|webm|mov|svg)$/i.test(path)) return url;

  return getPreviewUrl(url, { width: opts.width, quality: opts.quality });
}

/**
 * Kept for compatibility. Car images are stored with their full URL in the
 * database, so this is only reachable if something still builds a URL by path.
 */
export function getCarStorageUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return appwriteFileUrl("car-images", path);
}

// Get cover image URL for a car
export function getCoverImage(car: {
  car_images?: { url: string; position: number }[];
}): string | null {
  if (!car?.car_images || car.car_images.length === 0)
    return "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800";
  const sorted = [...car.car_images].sort((a, b) => a.position - b.position);
  return (
    sorted[0]?.url ??
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800"
  );
}

// Format odometer --> "63,671 km"
export function formatOdometer(km: number): string {
  return `${new Intl.NumberFormat("en-AU").format(km)} km`;
}

// Format price --> "$48,990"
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
