import { ASSET_MAP } from "./assetMap";

// Appwrite Storage URL helpers.
//
// Appwrite storage is FLAT — there are no folder paths, only file ids. The
// original code passed human-readable paths like "Homepage/hero-poster.jpg",
// and those paths are hardcoded across 17 files, so rather than editing every
// call site we map path -> fileId here.
//
// ASSET_MAP is generated by migrate/migrate-assets.mjs. After uploading a new
// asset, re-run that script and copy the regenerated file over utils/assetMap.ts.

const ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT;
const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID;

function appwriteFileUrl(bucketId: string, fileId: string): string {
  return `${ENDPOINT}/storage/buckets/${bucketId}/files/${fileId}/view?project=${PROJECT_ID}`;
}

/**
 * Site assets — logos, banners, hero video, UI graphics.
 * Takes the same path it always did, e.g. "Homepage/lightshardleft.png".
 */
export function getAssetsStorageUrl(path: string): string {
  const fileId = ASSET_MAP[path];
  if (!fileId) {
    // Loud in development, silent in production: a missing asset should be
    // obvious while building but shouldn't spam production logs on every render.
    if (process.env.NODE_ENV !== "production") {
      console.warn(
        `[assets] No Appwrite file mapped for "${path}". ` +
          `Re-run migrate/migrate-assets.mjs and update utils/assetMap.ts.`,
      );
    }
    return "";
  }
  return appwriteFileUrl("assets", fileId);
}

/**
 * Kept for compatibility. Car images are stored with their full URL in the
 * database, so this is only reachable if something still builds a URL by path.
 */
export function getCarStorageUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return appwriteFileUrl("car-images", path);
}

// Get cover image URL for a car
export function getCoverImage(car: {
  car_images?: { url: string; position: number }[];
}): string | null {
  if (!car?.car_images || car.car_images.length === 0)
    return "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800";
  const sorted = [...car.car_images].sort((a, b) => a.position - b.position);
  return (
    sorted[0]?.url ??
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800"
  );
}

// Format odometer --> "63,671 km"
export function formatOdometer(km: number): string {
  return `${new Intl.NumberFormat("en-AU").format(km)} km`;
}

// Format price --> "$48,990"
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
